name: test

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests for (${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ "3.0", "3.1" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run specs
      run: bundle exec rake spec
